<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width"/>
<title>${title} Script</title>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href='./css/materialize/css/materialize.min.css' rel='stylesheet' type='text/css'>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="/css/materialize/js/materialize.min.js"></script>

<style type="text/css">
    
.story-block {
    height: 20px;
}


html {
    font-family: 'Courier New', Courier, 'Lucida Sans Typewriter', 'Lucida Typewriter', monospace;
    font-size: 12px;
    font-style: normal;
    font-variant: normal;
    font-weight: 400;
    line-height: 18px;
}

.page-footer {
    background-color: teal;
}

</style>


</head>

<body>


<div class="container">

    <div class="row">
        <div class="s12 col center-align">
            <h1>${title}</h1>
        </div>
        <hr>
    </div>

    <div class="row">
        <div class="s12 col">
            <p>${title_description}</p>
        </div>
    </div>

    <p>&nbsp</p>


%for cn, sbs in spoken_x_character.items():

    <div class="row">
    %for sb in sbs:
        <div class="s12 col">
            <h5>${sb.location.upper()}</h5>
            <h5>${sb.description}</h5>
        </div>
        <p>&nbsp</p>
        %for e_dict in sb.entries:
        <div class="s8 offset-s2 col center-align">


            %if not sb.IsGroupScene:

            <div class="row">
                <div class="s12 col center-align story-block">
                    <h5>${cn.upper()}</h5>
                </div>
                <div class="s10 offset-s2 col left-align story-block">
                    <p><i>(${e_dict['parenthetical']})</i></p>
                </div>
            </div>

            <div class="row">
                <div class="s12 col left-align">
                    <h6 class="flow-text">${e_dict['dialog']}</h6>
                </div>
            </div>

            %endif


        </div>

        %endfor
    %endfor
    </div>
%endfor

</div>


<p>&nbsp</p>
<p>&nbsp</p>
<p>&nbsp</p>
<p>&nbsp</p>

%if print_footer:

<footer class="page-footer teal lighten-2">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">${title}</h5>
                <p class="grey-text text-lighten-4">Game Script, generated by DialogC</p>
            </div>
            <div class="col l6 s12">
                <p class="grey-text text-lighten-4">Note: A DialogC compiled 'script' is designed for the responsive web and can not follow the strict formatting of a proper screenplay. It attemps to be a close approximation.</p>
            </div>
        </div>
    </div>
  <div class="footer-copyright">
    <div class="container">
    &#xA9; ${copyright}
    <a class="grey-text text-lighten-4 right" href="http://miga.io">MIGA</a>
    </div>
  </div>
</footer>

%endif




</body>

</html>




